### ISSUE TITLE
Daily games immediately after midnight sometimes still use solution from previous day

### ISSUE THREAD

**Issue by Teban54** [lazyguyy/survivle#18]
I've noticed this issue for a while now:

I often play the games within the first hour after midnight Eastern Time. Very often (if not always), the game would proceed using the solution from the previous day. I can either finish the game and arrive at that solution; or, if I leave the game halfway done and come back to it midday, the tiles would be updated to match the actual, "new" solution of the day, but breaking the game rule in the process.

The screenshot below was taken 5 minutes ago. I started this game probably around 1am EDT on August 10, and it was trending towards a game I already played the day before (can't remember the word but it started with GA).

![Screenshot_20240810_150013_Chrome](https://github.com/user-attachments/assets/0b029193-7f57-4022-82f4-03372c211763)

**Comment by lazyguyy** [comment]
Oh well this is bad. I can only imagine there is some date shenanigans happening in the background, but I am really not sure where the bug lies.
But I have two questions: Do you reload the page when you start playing shortly after midnight? And when you open the options page, what is the shown "solution" -- is it the word from two days ago or the word from yesterday (as in one hour ago)? I'll try to reproduce the bug on my side as well.

**Comment by Teban54** [comment]
1. In the past when this happened, I did try to refresh the page multiple times once I realized that the tiles were trending in the direction of yesterday's answer, but the tiles never changed.
2. I never checked the "Yesterday's Daily" info from the settings shortly after midnight, but as of now (when the current solution is the correct one, JUICE), "Yesterday's Daily" shows GAFFE, the answer from yesterday, 8/9.

The next time I encounter this, I will check (a) which solution I get on a different device or browser, and (b) what the "Yesterday's Solution" is shortly after midnight.

**Comment by Teban54** [comment]
This seems to have appeared again today, around 1am EDT on August 11.

From the settings, "Yesterday's Solution" was shown as GAFFE, which was actually from 2 days ago (8/9). The tiles were leading up to JUICE, the solution on 8/10. On a browser where I typed JUICE on first try, it was indeed the solution.

This behavior is consistent across: Chrome on my phone (where I initially noticed the problem), Chrome on PC, and Edge on PC. I have refreshed the page multiple times on each, and I have never played Survivle on PC before in either browser.

**Comment by lazyguyy** [comment]
Ok so the fact that the daily survivle rolls over to the next day is actually intended; As long as you don't reload the page the secret word remains the same, so you can still solve the previous day's puzzle if you started the puzzle and haven't reloaded the page since.
However, the browser will remember the date you last played a daily puzzle on (saving the date when you start that puzzle), and if you reload the page and the current date and the saved date don't match up, the cache gets cleared. The dates always change at midnight, and from my testing this seems to work.

However, I think I managed to find the bug. The issue was with the calculation of the daily word and this is because of daylight savings! Subtracting two dates in javascript gives their difference in milliseconds. I divided this difference by (1000 * 60 * 60 * 24) and floored it to get the difference in days. 
This almost always works, except when one of the days between the start date and the current date only has 23 hours due to daylight savings. Therefore it was possible to spend the first hour of the day solving for the previous day's secret word. 
I shifted the day difference calculation now explicitly to UTC dates since they are always 24 hours long. It should be working now!

Please let me know if there are still problems!
